version: "3.9"  # optional since v1.27.0
services:
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    restart: unless-stopped
    container_name: sql_server2022
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=A&VeryComplex123Password
    networks:
      - mynetwork

  web_api:
    restart: unless-stopped
    build: .  # build the Docker image
    container_name: web_api_application
    ports:
      - "7169:80"
    depends_on:
      - sql
    networks:
      - mynetwork

  rabbitmq:
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    environment:
    - RABBITMQ_DEFAULT_USER=myuser
    - RABBITMQ_DEFAULT_PASS=mypass
    labels:
      NAME: "rabbitmq"
    ports: 
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"
    depends_on:
      - web_api
    networks:
      - mynetwork

  rabbitmq_consumer:
    build: 
      context: .
      dockerfile: ./ConsumerServiceApp/Dockerfile
    links:
      - web_api
    depends_on:
      - web_api
      - sql
      - rabbitmq
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
